title: Fiyonk
description: My blog
url: "https://oakasapoglu.github.io"
baseurl: "/fiyonk"

# theme: minima
theme: jekyll-theme-midnight



markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
